### ISSUE TITLE
Trade Site crashes if specific name is used to save trade

### ISSUE THREAD

**Issue by RickTorresJr** [exile-center/better-trading#115] opened 2022-09-21 21:12 UTC
## Issue
The trade side will cease to load, even after closing and opening a new tab if the Better PathOfExile Trading bookmark was named:

 `Jewel - Cluster - Large -  Prismatic Heart / Sadist / Disorienting Display - Budget`

## How to replicate
* Name a trade bookmark with `Jewel - Cluster - Large -  Prismatic Heart / Sadist / Disorienting Display - Budget` (the search does not seem to matter. Happened with a Tabula search)
  * Original trade link that caused the problem: https://www.pathofexile.com/trade/search/Kalandra/r6kl48EtQ
* Only restarting Chrome will fix the trade site loading again (but will happen again if you search for the same Cluster Jewel)
* Browsers used:
  * Brave Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit) - Windows
  * Google Chrome Version 105.0.5195.127 (Official Build) (64-bit) - Windows

## What was tried
* Clearing all Chrome cache
* Reinstalling Better PathOfExile Trading Chrome extension
* Deleting all other bookmarks

<img width="298" alt="Named Trade Link Breaking Extension" src="https://user-images.githubusercontent.com/12430441/191610971-3305887f-03a3-4c73-87b0-79506e89ef6b.png">

<img width="329" alt="Tab Hung" src="https://user-images.githubusercontent.com/12430441/191611810-2e90db06-b453-49f6-bff0-adb4fe3d58fb.png">

<img width="569" alt="Out of Memory" src="https://user-images.githubusercontent.com/12430441/191612103-6a1c0002-5d15-4a17-9dcb-e81f31baff52.png">

<img width="844" alt="Working Extension After Renaming" src="https://user-images.githubusercontent.com/12430441/191611089-f07f66d8-6129-4125-a77a-f166bf706583.png">

Edit: Added more screenshots

**Comment by dbjorge** [comment] 2022-10-04 01:47
Hi @RickTorresJr ,

Thanks for reporting the issue! Unfortunately, I'm unable to reproduce it on my machine (in Chrome 105 or 106 on Windows).

* Do you have any other browser extensions and/or userscripts installed, especially any that might be interacting with the trade site or with page/tab titles in general?
* If so, are you able to reproduce the issue in a clean Chrome profile with only Better Trading installed?
![screenshot highlighting menu option to create a clean profile](https://user-images.githubusercontent.com/376284/193716445-0d55e44c-3a91-4be5-8bdc-e8f8669ad5f4.png)

**Comment by dbjorge** [comment] 2022-10-04 03:29
I added a fix for one potential way I could imagine this issue occurring if a different extension/userscript were to try to "fight" our new feature to rename page/tab titles (ie, if both us and a different extension kept detecting and trying to undo each others' attempts to rename the title differently) in https://github.com/exile-center/better-trading/commit/85794d12cebc51e7345629a782f0a02bb3ed1a77. That update will be included in the next release, but I'm not very optimistic that it will actually resolve your issue since I still haven't been able to reproduce it locally.

**Comment by dbjorge** [comment] 2022-10-04 05:51
The candidate fix from https://github.com/exile-center/better-trading/commit/85794d12cebc51e7345629a782f0a02bb3ed1a77 has been released in 1.7.1. It would be helpful if you could test and see if that helps the issue - but again, I'm just blindly guessing at what the issue might be without a local repro, so there's a good chance it won't help.

**Comment by RickTorresJr** [comment] 2022-10-07 19:38
@dbjorge Thank you for looking into this and apologies for taking a bit to turn this around. I'm unable to trigger the abnormal behavior after the 1.7.1 update both on Chrome and Brave.

![image](https://user-images.githubusercontent.com/12430441/194639466-95059a33-5055-4271-a0fd-9795d202d341.png)

The update seems to have fixed the problem. Before the update (when the Tab would hang) in Chrome, I did have several enabled extensions globally but Better PathOfExile Trading was the only PoE specific extension installed.

Thank you again!

**Comment by dbjorge** [comment] 2022-10-07 21:47
I'm glad to hear the update helped! I'll go ahead and close this issue; if you encounter it again, feel free to reopen it.

**Closed** 2022-10-07 21:48 UTC
Labels: bug, no repro
