### ISSUE TITLE
League Swap option

### ISSUE THREAD

**Issue by Fleymour** [exile-center/better-trading#132] opened 2023-08-18 02:32 UTC
hey i installed your exention today and i really love it . super easy super neat.

since the new league hasnt started ill only can add standart items.. so would be great to swap leagues for all items with 1 click / menu.
this would also neat if people want to share their lists with other players from other leagues or if 1 player plays different chars / leagues and just want to have 1 list per char / category ! 

(technically the option just need to edit text part of the item-link that the league ?)

**Comment by pboutin** [comment] 2023-08-18 13:24
Duplicate of https://github.com/exile-center/better-trading/issues/131

Thanks for the kind words.

**Closed by pboutin** 2023-08-18 13:24 UTC
