### ISSUE TITLE
Suggestions: Open all saved searches in a folder

### ISSUE THREAD

**Issue by niklaas-0rbit** [exile-center/better-trading#29] opened 2020-03-13 08:55 UTC
Possibility to open all saved searches in a folder in new tabs.

**Comment by barbarolucente** [comment] 2020-03-14 12:31
Yes please, would be awesome.

**Comment by pboutin** [comment] 2020-03-16 13:33
Duplicate of https://github.com/exile-center/better-trading/issues/20

This will ship in the next release :)

**Closed by pboutin** 2020-03-16 13:33 UTC
